[layout]
    shred_tile_count = 4
[tiles]
    [tiles.archiver]
        enabled = true
        end_slot = {end_slot}
        ingest_mode = "rocksdb"
        rocksdb_path = "{ledger}/rocksdb"
    [tiles.replay]
        cluster_version = "{cluster_version}"
    [tiles.gui]
        enabled = false
[funk]
    heap_size_gib = {funk_pages}
    max_account_records = {index_max}
    max_database_transactions = 64
[runtime]
    max_live_slots = 4
    max_fork_width = 4
    [runtime.program_cache]
        heap_size_mib = 4096
[consensus]
    vote = false
[development]
    sandbox = false
    no_agave = true
    no_clone = true
[log]
    level_stderr = "INFO"
    path = "{log}"
[paths]
    snapshots = "{ledger}"
[snapshots]
    incremental_snapshots = false
    [snapshots.sources]
        servers = []
        [snapshots.sources.gossip]
            allow_any = false
            allow_list = []
[gossip]
    entrypoints = [ "0.0.0.0:1" ]
